# Generated by Django 4.2 on 2023-05-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_return', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturnitem',
            name='foc',
        ),
    ]
