from django.urls import path
from .import views
urlpatterns = [
    path('usercount/', views.currentUserCount),
    path('today/distributor/<id>',
         views.today_as_distributor),
    path('today/salesref/<id>',
         views.today_as_saleref),
    path('today/manager/<id>',
         views.today_as_manager),
    path('today/inventory/notzero/company/',
         views.today_company_inventory_status),
    #     path('today/market-return/company/',
    #          views.today_market_return),
    path('get/allsales/company/months',
         views.allSalesinvoicedataBymonth),
    path('get/allsales/distributor/months/<id>',
         views.allSalesinvoicedataDistributorBymonth),
    path('get/allsales/manager/months/<id>',
         views.allSalesinvoicedataManagerBymonth),
    path('get/allsales/salesref/months/<id>',
         views.allSalesinvoicedataSalesRefBymonth),
    path('get/distributors/sales/<id>',
         views.allDistributorSalesByManager),
    path('get/lowqty/by/distributor/<id>',
         views.allLawQtyByDistributor),
    path('get/lowqty/by/salesref/<id>',
         views.allLawQtyBySalesref),
]
